### ISSUE TITLE
On Android Support

### ISSUE THREAD

**Issue by joseph-henry** [zerotier/libzt#119]
This ticket exists to replace the collection of other Android-related tickets that keep popping up.

In principle, there is nothing stopping libzt from running on Android, but designing a build process for an android AAR that uses the NDK is not easy. Inevitably some combination of gradle rot, NDK changes, and general android studio bugs prevent any build process from surviving long-term.

Ideally the AAR build process should take the form of a github action so that it is easily reproducible by everyone:

```
name: Build Android AAR

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init
      
    - name: Build
      run: ./build.sh android-aar "release"

    - uses: actions/upload-artifact@v2
      with:
        path: dist
```

Unfortunately the way in which github actions implements their symlinking to NDK paths makes this impossible without using some [mitigations](https://github.com/actions/virtual-environments/issues/2689) that don't seem to work anyway:

```
Observed package id 'ndk;21.4.7075529' in inconsistent location '/usr/local/lib/android/sdk/ndk-bundle' (Expected '/usr/local/lib/android/sdk/ndk/21.4.7075529')
```

Attempting to replicate this locally requires that I manually patch Android's `sdkmanager` as it's broken out of the box. Really? So unless someone knows how to resolve the above issue, we will not be officially supporting Android for the time being. It simply is not worth the trouble.

Relatedly,

The Java API has been significantly refreshed and the JAR can be built using [.github/workflows/jar.yaml](https://github.com/zerotier/libzt/blob/master/.github/workflows/jar.yaml)
 - Example API usage: [examples/java](https://github.com/zerotier/libzt/tree/master/examples/java/Example.java)
 - New docs: http://docs.zerotier.com/libzt-java
 - I'll be hosting a webinar on June 2nd where I will answer questions and discuss any feature requests you might have, sign up [here](https://my.demio.com/ref/1Oq3MSZWYJMtKQ0Z)
